#!/bin/csh
#SBATCH -J KHPX_download
#SBATCH -o KHPX_log.out
#SBATCH -e KHPX_log.err
#SBATCH --ntasks=1
#SBATCH --tasks-per-node=1
#SBATCH --exclusive
#SBATCH --mail-user=carmenchilson@ou.edu
#SBATCH --mail-type=ALL
#SBATCH -p swat_plus
#SBATCH -t  12:00:00
#SBATCH -D /home/cchilson/schoonerJobs/download_data/outfiles

set echo

date
python /home/cchilson/gitRepositories/BirdRoostDetection/BirdRoostDetection/PrepareData/downloadData.py KHPX ml_labels.csv /condo/swatwork/cchilson/OBS_research
